spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: ab123456
  application:
    name: goods-list   # 应用名

server:
  port: 8082

# 指定注册的服务中心地址，一般与eureka-server中配置的对应，此时该服务启动就会将自己注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true